### ISSUE TITLE
add `Astro` setup page

### ISSUE THREAD

**Issue by setodeve** [yamada-ui/yamada-docs#190]
### Subject

getting-started/frameworks/astro

### Description
We want to create a Yamada UI setup page using `Astro`.
Try `Astro`.

### Are you willing to participate in creating this documentation page and create a pull request?

Yes

**Comment by hirotomoyamada** [comment]
This issue has been moved due to repository consolidation.

https://github.com/yamada-ui/yamada-ui/issues/1366
