### ISSUE TITLE
変更された`pseudo`の`_weekend`, `_outside`の`CSS Property`を更新する

### ISSUE THREAD

**Issue by umaidashi** [yamada-ui/yamada-docs#199]
### 主題

_weekend, _outside

### 説明

[この課題](https://github.com/yamada-ui/yamada-ui/pull/967)で、`_weekend`,`_outside`のCSS　Propertyに`:where()`が追加されたため、その変更を反映する

### このドキュメントページの作成に参加し、プルリクエストを作成しますか？

はい

**Comment by hirotomoyamada** [comment]
That file is automatically generated. This issue will be closed.
