### ISSUE TITLE
Add Mail of Example page

### ISSUE THREAD

**Issue by hirotomoyamada** [yamada-ui/yamada-docs#204]
### Subject

Mail

### Description

We would like to create an example application using Yamada UI using [shadcn/ui](https://ui.shadcn.com/examples/mail) as a reference.

### Are you willing to participate in creating this documentation page and create a pull request?

None

**Comment by umaidashi** [comment]
I'm working on it now.

**Comment by hirotomoyamada** [comment]
Fixed
