### ISSUE TITLE
Add Dashboard of Example page

### ISSUE THREAD

**Issue by hirotomoyamada** [yamada-ui/yamada-docs#205]
### Subject

Dashboard

### Description

We would like to create an example application using Yamada UI using [shadcn/ui](https://ui.shadcn.com/examples/dashboard) as a reference.

### Are you willing to participate in creating this documentation page and create a pull request?

None

**Comment by tasukuwato** [comment]
Hello, plz let me contribute to this issue

**Comment by hirotomoyamada** [comment]
@tasukuwato 

Hi, I'll assign this issue to you!

**Comment by hirotomoyamada** [comment]
Fixed
