### ISSUE TITLE
Add Tasks of Example page

### ISSUE THREAD

**Issue by hirotomoyamada** [yamada-ui/yamada-docs#207]
### Subject

Tasks

### Description

We would like to create an example application using Yamada UI using [shadcn/ui](https://ui.shadcn.com/examples/tasks) as a reference.

### Are you willing to participate in creating this documentation page and create a pull request?

None

**Comment by mst-mkt** [comment]
Please let me contribute to this issue!

**Comment by hirotomoyamada** [comment]
Hi, I'll assign this issue to you!

**Comment by mst-mkt** [comment]
Thanks, I'll create a pull request once I've completed the work.

**Comment by hirotomoyamada** [comment]
Fixed
