### ISSUE TITLE
Add Forms of Example page

### ISSUE THREAD

**Issue by hirotomoyamada** [yamada-ui/yamada-docs#209]
### Subject

forms

### Description

We would like to create an example application using Yamada UI using [shadcn/ui](https://ui.shadcn.com/examples/forms) as a reference.

### Are you willing to participate in creating this documentation page and create a pull request?

None

**Comment by kaitobq** [comment]
asign

**Comment by setodeve** [comment]
@kaitobq 
Assign it to you. Let's try to contribute!

**Comment by hirotomoyamada** [comment]
Fixed
