### ISSUE TITLE
Add Music of Example page

### ISSUE THREAD

**Issue by hirotomoyamada** [yamada-ui/yamada-docs#210]
### Subject

music

### Description

We would like to create an example application using Yamada UI using [shadcn/ui](https://ui.shadcn.com/examples/music) as a reference.

### Are you willing to participate in creating this documentation page and create a pull request?

None

**Comment by Hayato1031** [comment]
Please let me contribute to this issue!

**Comment by hirotomoyamada** [comment]
Hi, I'll assign this issue to you.

**Comment by hirotomoyamada** [comment]
Fixed
