### ISSUE TITLE
Add Authentication of Example page

### ISSUE THREAD

**Issue by hirotomoyamada** [yamada-ui/yamada-docs#211]
### Subject

Authentication

### Description

We would like to create an example application using Yamada UI using [shadcn/ui](https://ui.shadcn.com/examples/authentication) as a reference.

### Are you willing to participate in creating this documentation page and create a pull request?

None

**Comment by TakayukiHirano117** [comment]
Can I contribute to this issue?

**Comment by hirotomoyamada** [comment]
Hi, I'll assign this issue to you!

**Comment by taroj1205** [comment]
Completed with #301
