### ISSUE TITLE
`Reorder` example is not working.

### ISSUE THREAD

**Issue by 108yen** [yamada-ui/yamada-docs#258]
### Provide the exact quote of the error or issue

Unable to sort by `Reorder` example.
It works correctly if managed by `useState`.

### Does the docs page already exist? Please link to it.

https://yamada-ui.com/ja/components/data-display/reorder

### Are you willing to participate in fixing this issue and create a pull request with the fix?

None

**Comment by hirotomoyamada** [comment]
@108yen 

This seems to be a bug in Reorder. Could you please create an issue in the Yamada UI repository?

After creating the issue, please close this issue.

**Comment by 108yen** [comment]
created
https://github.com/yamada-ui/yamada-ui/issues/1158
