### ISSUE TITLE
Add more information about hook's API

### ISSUE THREAD

**Issue by KenyaMasuko** [yamada-ui/yamada-docs#282]
### Subject

Hooks

### Description

While using [useClipboard](https://yamada-ui.com/hooks/use-clipboard), I felt the need for more information about the interface and APIs of the hooks. 

I think it would be more user-friendly if roles of args and return values like `onCopy` and `hasCopied` were clearly documented (like [Mantine](https://mantine.dev/hooks/use-clipboard/#api))!

### Are you willing to participate in creating this documentation page and create a pull request?

Yes

**Comment by hirotomoyamada** [comment]
This issue has been moved due to repository consolidation.

https://github.com/yamada-ui/yamada-ui/issues/1365
