### ISSUE TITLE
Fix link to author in examples page

### ISSUE THREAD

**Issue by taroj1205** [yamada-ui/yamada-docs#304]
### Subject

Examples

### Description

The links for `Created by` in `Cards` are not assigned to the correct person.
https://yamada-ui.com/examples/cards

### Are you willing to participate in creating this documentation page and create a pull request?

Yes

**Comment by hirotomoyamada** [comment]
This issue has been moved due to repository consolidation.

https://github.com/yamada-ui/yamada-ui/issues/1363
